In [1]:
!pip install tensorflowjs

    100% |████████████████████████████████| 307kB 12.8MB/s 
    100% |████████████████████████████████| 13.8MB 1.6MB/s 
    100% |████████████████████████████████| 61kB 11.5MB/s 
    100% |████████████████████████████████| 51kB 9.6MB/s 
tensorflow 1.12.0 has requirement keras-applications>=1.0.6, but you'll have keras-applications 1.0.4 which is incompatible.
tensorflow 1.12.0 has requirement keras-preprocessing>=1.0.5, but you'll have keras-preprocessing 1.0.2 which is incompatible.
cufflinks 0.14.6 has requirement plotly>=3.0.0, but you'll have plotly 1.12.12 which is incompatible.
astropy 2.0.10 has requirement pytest<3.7,>=2.8, but you'll have pytest 3.10.1 which is incompatible.
thinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.0 which is incompatible.
featuretools 0.4.1 has requirement pandas>=0.23.0, but you'll have pandas 0.22.0 which is incompatible.
  Found existing installation: numpy 1.14.6
    Uninstalling numpy-1.14.6:
      Successfully unin

In [2]:
!pip install gutenberg

    100% |████████████████████████████████| 1.2MB 12.2MB/s 
    100% |████████████████████████████████| 911kB 17.2MB/s 
    100% |████████████████████████████████| 1.0MB 14.5MB/s 
    100% |████████████████████████████████| 51kB 19.7MB/s 
    100% |████████████████████████████████| 573kB 21.2MB/s 
  Running setup.py bdist_wheel for gutenberg ... - done
  Stored in directory: /root/.cache/pip/wheels/8e/cd/75/4bc6f16541a1b7a69b02168da567695b2271c23ac4a0a0a453
  Running setup.py bdist_wheel for rdflib-sqlalchemy ... - done
  Stored in directory: /root/.cache/pip/wheels/8c/7f/e5/2cfedb41ce9149b8af8c35a063b4fd1b8c1573c6391bbd5b53
  Running setup.py bdist_wheel for rdflib ... - \ | / done
  Stored in directory: /root/.cache/pip/wheels/8d/f6/b7/f5e9501d0f006fc9fd497c930206952856b2191ab5c836cb97
  Running setup.py bdist_wheel for alembic ... - \ done
  Stored in directory: /root/.cache/pip/wheels/f3/a5/e1/0d0a52770a7249920a4c3404aeaff9fb7bc27adb9bda8f7c51
  Running setup.py bdi

In [0]:
# your github username
USER_NAME = "github_username" 

# the email associated with your commits
# (may not matter if you leave it as this)
#USER_EMAIL = "bar.com" 

# the user token you've created (see the lecture 8 slides for instructions)
TOKEN = "Your token" 

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "Site name"

In [0]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

In [5]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

Cloning into 'ujwalp1994.github.io'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 29 (delta 6), reused 29 (delta 6), pack-reused 0
Unpacking objects: 100% (29/29), done.


In [6]:
os.chdir(repo_path)
!git pull

Already up to date.


In [0]:
project_path = os.getcwd()
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

In [0]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

In [9]:
from gutenberg.acquire import load_etext
from gutenberg.cleanup import strip_headers
import itertools
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.models import Model
from keras.optimizers import RMSprop
from keras.callbacks import EarlyStopping

Using TensorFlow backend.


In [0]:
from nltk import tokenize
import re

In [11]:
import nltk as nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [0]:
def train_extraction(book_no):
  book = strip_headers(load_etext(book_no)).strip()
  book = book.encode('ascii', 'ignore')
  sentences = re.split(r' *[\.\?!][\'"\)\]]* *', book)
  sentences = [i.replace('\n','') for i in sentences]
  sliced_list = sentences[1:1001]
  return sliced_list

In [0]:
def test_extraction(book_no):
  book = strip_headers(load_etext(book_no)).strip()
  book = book.encode('ascii', 'ignore')
  sentences = re.split(r' *[\.\?!][\'"\)\]]* *', book)
  sentences = [i.replace('\n','') for i in sentences]
  test_slice = sentences[1002:1202]
  return test_slice

In [0]:
ariel_dance = train_extraction(58412)
billiard_room = train_extraction(58413)
river_life = train_extraction(58406)
areil_test = test_extraction(58412)
billiard_test = test_extraction(58413)
river_test = test_extraction(58406)

Checking size and first sentence of each of the books

In [15]:
print "Size of Ariel dance:\t", len(ariel_dance), "\nFirst sentence: \t", ariel_dance[0]
print "\nSize of Billiard room:\t", len(billiard_room), "\nFirst sentence: \t", billiard_room[0]
print "\nSize of River of life:\t", len(river_life), "\nFirst sentence: \t", river_life[0]

Size of Ariel dance:	1000 
First sentence: 	No one would be likely to look at her twice orgive her a second thought, as she crouched away from the March wind,insufficiently protected from the cold by her nondescript tweed coat,and carelessly, casually bare-headed

Size of Billiard room:	1000 
First sentence: 	S

Size of River of life:	1000 
First sentence: 	THE RIVER OF LIFE  THE RIVER OF LIFE  AND OTHER STORIES  BY  ALEXANDER KUPRIN  TRANSLATED FROM THE RUSSIAN BY  S


In [0]:
x_train = itertools.chain(ariel_dance, billiard_room, river_life)
x_train = list(x_train)

In [17]:
x_train[2000]

'THE RIVER OF LIFE  THE RIVER OF LIFE  AND OTHER STORIES  BY  ALEXANDER KUPRIN  TRANSLATED FROM THE RUSSIAN BY  S'

In [0]:
y_train = []
j = 0
for i in range(3000):
  if i == 999:
    j=j+1
  if i == 1999:
    j=j+1
  y_train.append(j)

Trying to tokenize the data

In [0]:
max_len = 150
num_words = 1000
from keras.preprocessing.text import Tokenizer
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

In [20]:
print(t.word_index)

{'raining': 4463, 'toogenuinely': 3142, 'confusedher': 3320, 'fawe': 3553, 'sowell': 4697, 'yellow': 430, 'four': 531, 'woods': 1716, 'hanging': 3386, 'rememberedfrom': 5650, 'hismothers': 1558, 'sunlit': 2865, 'tomiss': 3217, 'easilyscared': 6259, 'onepoliceman': 6075, 'lord': 1291, 'floorseven': 4198, 'aswarthy': 5421, 'sharingwith': 4202, 'bringing': 1652, 'agreeting': 2793, 'wooden': 2103, 'satchel': 2063, 'gardenabout': 4464, 'twodelightful': 5427, 'commented': 2524, 'herdesire': 2265, 'makesout': 5131, 'pulse': 2577, 'elegant': 2223, 'second': 243, 'valiant': 5193, 'shrugging': 3448, 'sailed': 3548, 'scraped': 1956, 'snuggled': 3528, 'blouse': 2087, 'ruthless': 4927, 'fingers': 476, 'morearticulate': 2494, 'shocks': 3225, 'writertoo': 6423, 'ratherthan': 4951, 'interrupting': 6380, 'here': 74, 'maryill': 3943, 'hers': 465, 'magnificentlyparted': 5195, 'tobecome': 2423, 'natured': 5539, 'substance': 1555, 'pokedtheir': 5182, 'military': 801, 'senseof': 4473, 'golden': 1599, 'nosub

In [0]:
sequences = t.texts_to_sequences(x_train)

In [0]:
from keras.preprocessing.sequence import pad_sequences
seq_matrix = pad_sequences(sequences, maxlen=max_len, padding='post')

In [23]:
print(seq_matrix)

[[ 50  36  51 ...   0   0   0]
 [ 24  55  14 ...   0   0   0]
 [  1 259  11 ...   0   0   0]
 ...
 [ 65  72 239 ...   0   0   0]
 [ 65 212 766 ...   0   0   0]
 [  2   1  44 ...   0   0   0]]


In [0]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

Trying RNN, adding LSTM layers

In [0]:
def RNN():
    inputs = Input(name='inputs',shape=[max_len])
    layer = Embedding(num_words,8,input_length=max_len)(inputs)
    layer = LSTM(164)(layer)
    layer = Dense(512,name='FC1')(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(1,name='out_layer')(layer)
    layer = Activation('sigmoid')(layer)
    rnn_model = Model(inputs=inputs,outputs=layer)
    return rnn_model

In [26]:
rnn_model = RNN()
rnn_model.summary()
rnn_model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          (None, 150)               0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 150, 8)            8000      
_________________________________________________________________
lstm_1 (LSTM)                (None, 164)               113488    
_________________________________________________________________
FC1 (Dense)                  (None, 512)               84480     
_________________________________________________________________
activation_1 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
out_layer (Dense)            (None, 1)                 513       
__________

In [27]:
rnn_model.fit(seq_matrix,y_train,batch_size=128,epochs=10)

Epoch 1/10
3000/3000 [==============================] - 16s 5ms/step - loss: 0.2318 - acc: 0.3330
Epoch 2/10
3000/3000 [==============================] - 14s 5ms/step - loss: 0.0446 - acc: 0.3333
Epoch 3/10
3000/3000 [==============================] - 15s 5ms/step - loss: -0.0106 - acc: 0.3333
Epoch 4/10
3000/3000 [==============================] - 14s 5ms/step - loss: -0.0084 - acc: 0.3333
Epoch 5/10
3000/3000 [==============================] - 14s 5ms/step - loss: -0.0066 - acc: 0.3333
Epoch 6/10
3000/3000 [==============================] - 14s 5ms/step - loss: -0.0106 - acc: 0.3333
Epoch 7/10
3000/3000 [==============================] - 14s 5ms/step - loss: -0.0106 - acc: 0.3333
Epoch 8/10
3000/3000 [==============================] - 14s 5ms/step - loss: -0.0106 - acc: 0.3333
Epoch 9/10
3000/3000 [==============================] - 14s 5ms/step - loss: -0.0106 - acc: 0.3333
Epoch 10/10
3000/3000 [==============================] - 14s 5ms/step - loss: -0.0106 - acc: 0.3333


Testing the sequential model

In [28]:
embedding_size = 8
n_classes = 3
epochs = 10

import keras
model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 150, 8)            8000      
_________________________________________________________________
flatten_1 (Flatten)          (None, 1200)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 3603      
Total params: 11,603
Trainable params: 11,603
Non-trainable params: 0
_________________________________________________________________


In [29]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
print(x_train)

[[ 50  36  51 ...   0   0   0]
 [ 24  55  14 ...   0   0   0]
 [  1 259  11 ...   0   0   0]
 ...
 [ 65  72 239 ...   0   0   0]
 [ 65 212 766 ...   0   0   0]
 [  2   1  44 ...   0   0   0]]


In [30]:
model.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
3000/3000 [==============================] - 0s 116us/step - loss: 1.0955 - acc: 0.3593
Epoch 2/10
3000/3000 [==============================] - 0s 45us/step - loss: 1.0614 - acc: 0.4903
Epoch 3/10
3000/3000 [==============================] - 0s 45us/step - loss: 0.9876 - acc: 0.5943
Epoch 4/10
3000/3000 [==============================] - 0s 43us/step - loss: 0.8989 - acc: 0.6790
Epoch 5/10
3000/3000 [==============================] - 0s 44us/step - loss: 0.8113 - acc: 0.7113
Epoch 6/10
3000/3000 [==============================] - 0s 43us/step - loss: 0.7356 - acc: 0.7460
Epoch 7/10
3000/3000 [==============================] - 0s 44us/step - loss: 0.6716 - acc: 0.7627
Epoch 8/10
3000/3000 [==============================] - 0s 43us/step - loss: 0.6184 - acc: 0.7853
Epoch 9/10
3000/3000 [==============================] - 0s 44us/step - loss: 0.5742 - acc: 0.7977
Epoch 10/10
3000/3000 [==============================] - 0s 44us/step - loss: 0.5368 - acc: 0.8103




```
The sequential model gives better accuracy
```



Creating test data

In [0]:
X_test = itertools.chain(areil_test, billiard_test, river_test)
X_test = list(X_test)

In [32]:
test_seq = t.texts_to_sequences(X_test)
test_seq_matrix = pad_sequences(test_seq, maxlen=max_len)
print(test_seq_matrix)

[[  0   0   0 ... 401  16   2]
 [  0   0   0 ...   2  23   4]
 [  0   0   0 ...   6   6   2]
 ...
 [  0   0   0 ... 322  24  29]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


Extracting test sentences to fit into the javascript

In [33]:
print "Ariel Dance test sentence:\t", areil_test[0], "\nBilliard room test sentence:\t", billiard_test[0], "\nRiver of Life test sentence:\t", river_test[2]

Ariel Dance test sentence:	Ariel, who had been promised a meeting withHughs sister, was taken aback and left wordless at this meeting with akimono and mules instead 
Billiard room test sentence:	As I said to you previously, there are so manythings that dont fit, they seem extraneous to the real core of thecrimeall the same, at the risk of becoming monotonous, I think I cansee a glimmer of light 
River of Life test sentence:	So you think they may win


In [34]:
preds = model.predict(test_seq_matrix)
print(preds)
import numpy as np
print(np.argmax(preds))

[[0.15663847 0.220835   0.6225265 ]
 [0.20020522 0.2583551  0.5414397 ]
 [0.179242   0.25921658 0.5615415 ]
 ...
 [0.24611509 0.22343498 0.5304499 ]
 [0.21916594 0.20304501 0.57778907]
 [0.21916594 0.20304501 0.57778907]]
302


In [35]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /content/ujwalp1994.github.io/model_js


In [0]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Project Gutenberg
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Ariel Dance</option>
      <option value="example2">The Billiard room</option>
      <option value="example3">The River of Life</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [0]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      'Ariel, who had been promised a meeting withHughs sister, was taken aback and left wordless at this meeting with akimono and mules instead',
  'example2':
      'As I said to you previously, there are so manythings that dont fit, they seem extraneous to the real core of thecrimeall the same, at the risk of becoming monotonous, I think I cansee a glimmer of light ',
  'example3':
      'So you think they may win'      
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [0]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [39]:
!ls

index.html  index.js  model_js


In [40]:
!git add . 
!git commit -m "colab -> github"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

[master 844cf76] colab -> github
 2 files changed, 1 insertion(+), 1 deletion(-)
 rewrite model_js/group1-shard1of1 (99%)
 rewrite model_js/model.json (81%)
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 42.55 KiB | 14.18 MiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/ujwalp1994/ujwalp1994.github.io/
   c7b620e..844cf76  master -> master


In [47]:
print "Now, visit\n",(SITE_NAME)

Now, visit
https://ujwalp1994.github.io
